# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: azisetup.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.choice import ChoiceData

from anag.basetab import UnoZeroCheckBox


class RegimeFiscaleChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[n for n in range(1,19,1)])


# Window functions

ID_TEXT = 10000
ID_TEXTCTRL = 10001
ID_REGFISC = 10002
ID_FOREIGN = 10003
ID_CHECKBOX = 10004

def FatturaElettronicaFiller( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Dati per la Fattura Elettronica" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item5 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item6 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetName( "setup_azienda_ftel_nome" )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item8 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "setup_azienda_ftel_cognome" )
    item5.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.AddGrowableCol( 0 )

    item5.AddGrowableCol( 2 )

    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Stabile organizzazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item11 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item12 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [250,-1], 0 )
    item12.SetName( "setup_azienda_ftel_soind" )
    item3.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item14 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item15 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item15.SetName( "setup_azienda_ftel_socap" )
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item16 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item16.SetName( "setup_azienda_ftel_socit" )
    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item17.SetName( "setup_azienda_ftel_sopro" )
    item14.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 1 )

    item3.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Dati azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item19, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Regime fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item22 = RegimeFiscaleChoice( parent, ID_REGFISC, wx.DefaultPosition, [100,-1], 
        ["RF01 - Ordinario","RF02 - Contribuenti minimi (art. 1, c.96-117, L. 244/2007)","RF03 - Nuove iniziative produttive (art.13, L. 388/2000)","RF04 - Agricoltura e attività connesse e pesca (artt. 34 e 34-bis, D.P.R. 633/1972)","RF05 - Vendita sali e tabacchi (art. 74, c.1, D.P.R. 633/1972)","RF06 - Commercio dei fiammiferi (art. 74, c.1, D.P.R.633/1972)","RF07 - Editoria (art. 74, c.1, D.P.R. 633/1972)","RF08 - Gestione di servizi di telefonia pubblica (art. 74, c.1,D.P.R. 633/1972)","RF09 - Rivendita di documenti di trasporto pubblico e di sosta (art. 74, c.1, D.P.R. 633/1972)","RF10 - Intrattenimenti, giochi e altre attività di cui alla tariffa allegata al D.P.R. n. 640/72 (art. 74, c.6, D.P.R.633/1972)","RF11 - Agenzie di viaggi e turismo (art. 74-ter, D.P.R. ","RF12 - Agriturismo (art. 5, c.2, L. 413/1991)","RF13 - Vendite a domicilio (art. 25-bis, c.6, D.P.R. 600/1973)","RF14 - Rivendita di beni usati, di oggetti d’arte, d’antiquariato o ","RF15 - Agenzie di vendite all’asta di oggetti d’arte, antiquariato ","RF16 - IVA per cassa P.A. (art. 6, c.5, D.P.R. 633/1972)","RF17 - IVA per cassa soggetti con volume d’affari inferiore a Eur 200.000 (art. 7, D.L. 185/2008)","RF19 - Regime forfettario (art.1, c.54-89, L. 190/2014)","RF18 - Altro"] , 0 )
    item22.SetName( "setup_azienda_ftel_regfisc" )
    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21.AddGrowableCol( 0 )

    item3.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Dati REA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item24, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Num.Iscriz:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item25, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item27 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item27.SetName( "setup_azienda_ftel_reanum" )
    item26.Add( item27, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item28 = wx.StaticText( parent, ID_TEXT, "Ufficio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item28, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item29 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item29.SetName( "setup_azienda_ftel_reauff" )
    item26.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Capitale sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item31 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item32 = NumCtrl(parent, integerWidth=6, fractionWidth=2, allowNegative=False); item32.SetName('setup_azienda_ftel_capsoc')
    item31.Add( item32, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item33 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Socio unico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.SetName( "setup_azienda_ftel_socuni" )
    item31.Add( item33, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item34 = UnoZeroCheckBox( parent, ID_CHECKBOX, "In liquidazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.SetName( "setup_azienda_ftel_socliq" )
    item31.Add( item34, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.AddGrowableCol( 1 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item36 = wx.StaticBox( parent, -1, "Rappresentante fiscale" )
    item35 = wx.StaticBoxSizer( item36, wx.VERTICAL )
    
    item37 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item38 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item38, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item39 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item40 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetName( "setup_azienda_ftel_rfnome" )
    item39.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item41 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item41, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item42 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "setup_azienda_ftel_rfcognome" )
    item39.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item39.AddGrowableCol( 0 )

    item39.AddGrowableCol( 2 )

    item37.Add( item39, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item43 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item43, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item44 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [250,-1], 0 )
    item44.SetName( "setup_azienda_ftel_rfdes" )
    item37.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item45 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item45, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item46 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "setup_azienda_ftel_rfind" )
    item37.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item47 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item47, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item48 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item49 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item49.SetName( "setup_azienda_ftel_rfcap" )
    item48.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item50 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.SetName( "setup_azienda_ftel_rfcit" )
    item48.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item51 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item51.SetName( "setup_azienda_ftel_rfpro" )
    item48.Add( item51, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item48.AddGrowableCol( 1 )

    item37.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item52, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item53 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item54 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item54.SetName( "setup_azienda_ftel_rfcodfis" )
    item53.Add( item54, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item55 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.Add( item55, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item56 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item56.SetName( "setup_azienda_ftel_rfpiva" )
    item53.Add( item56, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item53.AddGrowableCol( 1 )

    item37.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item57 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.Add( item57, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item58 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item58.SetName( "setup_azienda_ftel_rfstato" )
    item37.Add( item58, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item37.AddGrowableCol( 1 )

    item35.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
