# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: cfg_fatturapa.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.numctrl import NumCtrl
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.radiobox import RadioBox



# Window functions

ID_TEXT = 10000
ID_FOREIGN = 10001
ID_NOTEBOOK = 10002
ID_BUTUPD = 10003

def FatturaElettronicaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Ultima trasmissione numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3 = NumCtrl(parent, integerWidth=5, fractionWidth=0, allowNegative=False); item3.SetName('ftel_numprogr')
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.Notebook( parent, ID_NOTEBOOK, wx.DefaultPosition, wx.DefaultSize, 0 )
    item4 = item5
    
    item6 = wx.Panel( item5, -1 )
    ClientiFunc(item6, False)
    item5.AddPage( item6, "Clienti destinatari" )

    item7 = wx.Panel( item5, -1 )
    ModPagamentoFunc(item7, False)
    item5.AddPage( item7, "Mod.Pagamento" )

    item8 = wx.Panel( item5, -1 )
    AliqIvaFunc(item8, False)
    item5.AddPage( item8, "Aliquote IVA" )

    item9 = wx.Panel( item5, -1 )
    DocumentiDaTrasmettereFunc(item9, False)
    item5.AddPage( item9, "Causali da trasmettere" )

    item10 = wx.Panel( item5, -1 )
    OpzioniFunc(item10, False)
    item5.AddPage( item10, "Opzioni" )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.Button( parent, ID_BUTUPD, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "butupd" )
    item0.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDTPD = 10004

def DocumentiDaTrasmettereFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Documenti da trasmettere:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDTPD, wx.DefaultPosition, [300,160], wx.SUNKEN_BORDER )
    item2.SetName( "pangridtpd" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_RADIOBOX = 10005
ID_TEXTCTRL = 10006
ID_CHECKBOX = 10007
ID_BUTSAVE = 10008

def TipoDocumentoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.RadioBox( parent, ID_RADIOBOX, "Tipo documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Non gestito","TD01 - Fattura","TD02 - Acconto/Anticipo su fattura","TD03 - Acconto/Anticipo su parcella","TD04 - Nota di Credito","TD05 - Nota di Debito","TD06 - Parcella"] , 1, wx.RA_SPECIFY_COLS )
    item1.SetName( "tipodocumento" )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticBox( parent, -1, "Formato di stampa" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Nome report:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item6 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item6.SetName( "toolprint" )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item4.AddGrowableCol( 1 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = wx.StaticBox( parent, -1, "Documento DDT" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "Doc.Trasporto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.CheckBox( parent, ID_CHECKBOX, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "isddt" )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.Button( parent, ID_BUTSAVE, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetName( "butsave" )
    item0.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDCLI = 10009

def ClientiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Clienti destinatari di fattura elettronica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDCLI, wx.DefaultPosition, [500,200], wx.SUNKEN_BORDER )
    item2.SetName( "pangridcli" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LINE = 10010

def DatiClienteFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Codice cliente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item3.SetName( "codice" )
    item3.Enable(False)
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item5 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [300,-1], 0 )
    item5.SetName( "descriz" )
    item5.Enable(False)
    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Codice destinatario P.A.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item7 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item7.SetFont( wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item7.SetName( "ftel_codice" )
    item1.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.Button( parent, ID_BUTSAVE, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "butsave" )
    item0.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDMPA = 10011

def ModPagamentoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Mod.Pagamento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDMPA, wx.DefaultPosition, [500,200], wx.SUNKEN_BORDER )
    item2.SetName( "pangridmpa" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TIPORATE = 10012
ID_MODPAG = 10013

def DatiModPagamentoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = RadioBox( parent, ID_TIPORATE, "Tipologia:", wx.DefaultPosition, wx.DefaultSize, 
        ["TP01 - Pagamento a rate","TP02 - Pagamento completo","TP03 - Anticipo"] , 1, wx.RA_SPECIFY_ROWS )
    item1.SetName( "tiporate" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = RadioBox( parent, ID_MODPAG, "Tipologia:", wx.DefaultPosition, wx.DefaultSize, 
        ["MP01 - Contanti","MP02 - Assegno","MP03 - Assegno circolare","MP04 - Contanti presso Tesoreria","MP05 - Bonifico","MP06 - Vaglia cambiario","MP07 - Bollettino bancario","MP08 - Carta di pagamento","MP09 - RID","MP10 - RID utenze","MP11 - RID veloce","MP12 - RIBA","MP13 - MAV","MP14 - Quietanza erario","MP15 - Giroconto su conti di contabilità speciale","MP16 - Domiciliazione bancaria","MP17 - Domiciliazione postale","MP18 - Bollettino di c/c postale","MP19 - SEPA Direct Debit","MP20 - SEPA Direct Debit CORE","MP21 - SEPA Direct Debit B2B"] , 2, wx.RA_SPECIFY_COLS )
    item2.SetName( "modpagamento" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.Button( parent, ID_BUTSAVE, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "butsave" )
    item0.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDIVA = 10014

def AliqIvaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Natura aliquote IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDIVA, wx.DefaultPosition, wx.DefaultSize, wx.SUNKEN_BORDER )
    item2.SetName( "pangridiva" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def DatiAliqIvaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = RadioBox( parent, ID_RADIOBOX, "Natura", wx.DefaultPosition, wx.DefaultSize, 
        ["-","N1 - Escluso ex Art.15","N2 - Non soggetto","N3 - Non imponibile","N4 - Esente","N5 - Regime del margine","N6 - Inversione contabile (reverse chanrge)"] , 1, wx.RA_SPECIFY_COLS )
    item1.SetName( "naturaliqiva" )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.Button( parent, ID_BUTSAVE, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.SetName( "butsave" )
    item0.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def OpzioniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Considera righe descrittive", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.CheckBox( parent, ID_CHECKBOX, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.SetName( "flagdescriz" )
    item0.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
